### ISSUE TITLE
Passing multiple items to an Option

### ISSUE THREAD

**Issue by mrboring** [JordanMarr/FSharp.SystemCommandLine#12]
Hi

I've been going through your examples and I'm having an issue with [Creating a Root Command Parser](https://github.com/JordanMarr/FSharp.SystemCommandLine#creating-a-root-command-parser). It works with multiple `-w`. Example:

```
dotnet run -- -w "aaa" -w "bbb" -w "ccc" -s "#"
```

How can I get it to work passing multiple values to a single `-w`? Example:

```
dotnet run -- -w "aaa" "bbb" "ccc" -s "#"
```

I did some searching and found [`Option.AllowMultipleArguments`](https://learn.microsoft.com/en-us/dotnet/api/system.commandline.option.allowmultipleargumentspertoken#system-commandline-option-allowmultipleargumentspertoken), but could not get it to work.

**Comment by mrboring** [comment]
I think I've found the solution by reading further through your examples. It was in [Defining Inputs Manually](https://github.com/JordanMarr/FSharp.SystemCommandLine#defining-inputs-manually)

By using `System.CommandLine.Option` I was able to add `opt.AllowMultipleArgumentsPerToken <- true` and this worked.

**Comment by JordanMarr** [comment]
Glad you found a solution. 👍
