### ISSUE TITLE
Subtleties between argv-fetching methods

### ISSUE THREAD

**Issue by baronfel** [JordanMarr/FSharp.SystemCommandLine#2]
This discussion is still a bit of a work-in-progress, but there are differences in how .NET apps get command line args that I wanted to bring up for discussion here because of [this line](https://github.com/JordanMarr/FSharp.SystemCommandLine/blob/main/src/FSharp.SystemCommandLine/CommandBuilders.fs#L240).

![arg-methods](https://user-images.githubusercontent.com/573979/158396495-aa0cf23c-c6ee-4060-a4e1-ae853b4209ad.png)

Here the differences between the three main methods of getting the args are shown:

* args passed to Main in a .NET app
* Environment.GetCommandLineArgs()
* Environment.CommandLine

the main thing is that there's a material difference between the first two, and that can impact the way that RootCommands parse args.  I don't really have anything actionable here, other than to wish that the args passed to the application were used instead somehow? Maybe by having the `Run` member return an `argv: string[] -> int/Task<int>` function instead?

I _think_ the goal of [this PR at System.CommandLine](https://github.com/dotnet/command-line-api/pull/1671/files) is to make the library not care which mechanism is used (which mostly is important for tab-completion, IIRC), so maybe in a few weeks this will all not matter anyway.

**Comment by JordanMarr** [comment]
I was using the `Parser` last night as a way to handle my unit tests using a single input args string; I noticed that it has an overload to handle either a `string` or `string[]`, so I tried it here and it looks promising!

```F#
[<EntryPoint>]
let main argv = 

    let parser = Parser()
    let mapResult (result: ParseResult) = result.Tokens |> Seq.map (fun t -> t.Value) |> Seq.toArray

    printfn "args"
    argv |> printfn "- Not Parsed:\t%A" 
    argv |> parser.Parse |> mapResult |> printfn "- Parsed:\t%A"
    printfn ""

    printfn "GetCommandLineArgs()"
    Environment.GetCommandLineArgs() |> printfn "- Not Parsed:\t%A" 
    Environment.GetCommandLineArgs() |> parser.Parse |> mapResult |> printfn "- Parsed:\t%A"
    printfn ""

    printfn "Environment.CommandLine"
    Environment.CommandLine |> printfn "- Not Parsed:\t%A" 
    Environment.CommandLine |> parser.Parse |> mapResult |> printfn "- Parsed:\t%A"
```

```bat
args
- Not Parsed:   [|"-w"; "hello"; "-w"; "world"|]
- Parsed:       [|"-w"; "hello"; "-w"; "world"|]

GetCommandLineArgs()
- Not Parsed:   [|"C:\_github\FSharp.SystemCommandLine\src\TestConsole\bin\Debug\net6.0\TestConsole.dll";
  "-w"; "hello"; "-w"; "world"|]
- Parsed:       [|"-w"; "hello"; "-w"; "world"|]

Environment.CommandLine
- Not Parsed:   "C:\_github\FSharp.SystemCommandLine\src\TestConsole\bin\Debug\net6.0\TestConsole.dll -w hello -w world"
- Parsed:       [|"-w"; "hello"; "-w"; "world"|]
```

So maybe we need to manually call `Parse` in the builder...
Or, as you mentioned, maybe it already is (or will be) parsed automatically. 🤔

Parsing manually in the builder would guarantee safety at the expense of possibly being redundant.

**Comment by JordanMarr** [comment]
This feels right:

```F#
    /// Executes a Command with a handler that returns unit.
    member this.Run (spec: CommandSpec<'Inputs, unit>) =
        this.CommandLineBuilder.Command
        |> this.SetGeneralProperties spec
        |> this.SetActionHandler spec
        |> ignore
        this.CommandLineBuilder.Build().Parse(args).Invoke()

    /// Executes a Command with a handler that returns a Task.
    member this.Run (spec: CommandSpec<'Inputs, Task<unit>>) =
        this.CommandLineBuilder.Command
        |> this.SetGeneralProperties spec
        |> this.SetFuncHandler spec
        |> ignore
        this.CommandLineBuilder.Build().Parse(args).InvokeAsync()

```

**Comment by baronfel** [comment]
I really would like to discourage the use of `Environment.GetCommandLineArgs()` as much as possible - while it's part of the runtime, most folks should probably just use the `argv` array passed in from Main. We (the System.CommandLine team) tend to think that any manual use of the command line is an advanced scenario and so shouldn't be encouraged.
