### ISSUE TITLE
For support in command builder

### ISSUE THREAD

**Issue by kentcb** [JordanMarr/FSharp.SystemCommandLine#5]
Hello again,

I was wondering whether it would be possible to add `For` support to the CE builder? My use case is wanting to generate child commands based on a pre-defined list. Something like:

```fsharp
command "visualizations" {
    description "Generate visualizations from data within the specified range."
    inputs (createDatabaseOption (), createStartingOption (), createEndingOption (), createOutputDirectoryOption ())
    setHandler handler

    for visualizationDefinition in visualizationDefinitions do
        setCommand (createVisualizationCommand visualizationDefinition)
}

```

This of course fails due to lack of `For` in the builder. I can do this "manually" by calling `AddCommand` on the command produced by the CE, but it's not as nice.

If you're wondering, the use case here is a parent command (`visualizations`) that contains a fixed number of child commands. Executing the parent command will generate all visualizations, but the user can also choose to execute each visualization in isolation. Since every visualization command involves the same logic, it will make the implementation easier to declare a static list of definitions and generate the subcommands based on that.

**Comment by JordanMarr** [comment]
I got you covered in [v0.8.0](https://github.com/JordanMarr/FSharp.SystemCommandLine/releases/tag/v0.8.0-beta).

NOTES:
* `setCommand` has been deprecated in favor of `addCommand` or `addCommands`
* I'm generally trying to stay close to the terminology of the underlying framework, so `addCommand` is a better fit than `setCommand`.
* I considered using `[<ParamArray>]`, but that enforces using an array and most F# devs prefer lists, so I went with separate, explicit operations that take either a single `Command` or a `Command seq`.
* This implementation is faster and easier to implement
