### ISSUE TITLE
Creating options with IsRequired = true

### ISSUE THREAD

**Issue by kentcb** [JordanMarr/FSharp.SystemCommandLine#6]
Hello,

My understanding of `Option.IsRequired` is that it can be set to `true` to force the user to provide a value for an option _even if there is no default value_. That said, when I played directly with `System.CommandLine` it appeared as though that behavior was currently broken (don't quote me on that - I'd have to double-check). Even so, it appears as though there is no way to specify that an option should be marked required without passing a default for it, so I'm wondering whether there can be.

**Comment by JordanMarr** [comment]
You can manually instantiate an `Option` and configure it however you want.
Then you just need to wrap it in a `HandlerInput`.

NOTE: You can `open FSharp.SystemCommandLine.Aliases` to provides access to the `Opt` alias for convenience so you don't get into naming conflicts between S.CL `Option` and F# `Option` types.

```F#
module Program

open FSharp.SystemCommandLine
open FSharp.SystemCommandLine.Aliases

let app (words: string array, separator: string option) =
    let separator = separator |> Option.defaultValue ", "
    System.String.Join(separator, words) |> printfn "Result: %s"
    0
    
[<EntryPoint>]
let main argv = 
    let words = Opt([| "--word"; "-w" |], IsRequired = true) |> HandlerInput.OfOption
    let separator = Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")
    
    let firstName = Opt([|"--first-name"; "-fn" |], IsRequired = true)



    rootCommand argv {
        description "Appends words together"
        inputs (words, separator)
        setHandler app
    }
```

**Comment by kentcb** [comment]
Thanks @JordanMarr - makes sense. But it does feel a little odd to need to do things differently depending on whether an argument is required or not. Do you think it could find a place in the `Input.Option[Maybe]` APIs? I could imagine something like:

```fsharp
Input.Option([ "--value"; "-v" ], isRequired = false)
```

**Comment by JordanMarr** [comment]
Yeah I suppose it could be added as an optional argument.

**Comment by JordanMarr** [comment]
I'm still not sure what all should be packed into the Input helper methods, so I'm a little hesitant to keep adding things and having tons of overloads for each property. 

To save you from my indecision, you may want to add this to your project as an extension for now:

```F#
[<AutoOpen>]
module InputExtensions = 
    
    open System.CommandLine

    type Input with 

        /// Creates a CLI option of type 'T.
        static member Option<'T>(name: string, ?description: string, ?isRequired) =
            Option<'T>(
                name,
                description = (description |> Option.defaultValue null)
            )
            |> fun opt -> opt.IsRequired <- isRequired |> Option.defaultValue false; opt
            |> HandlerInput.OfOption

        /// Creates a CLI option of type 'T.
        static member Option<'T>(aliases: string seq, ?description: string, ?isRequired) = 
            Option<'T>(
                aliases |> Seq.toArray,
                description = (description |> Option.defaultValue null)
            )
            |> fun opt -> opt.IsRequired <- isRequired |> Option.defaultValue false; opt
            |> HandlerInput.OfOption
```

**Comment by JordanMarr** [comment]
Alternatively, I could add one more generalized overload that takes a `configure` function that allows you to set as many properties as you want:

Like this:

```F#
[<EntryPoint>]
let main argv = 
    let words = Input.Option(["--word"; "-w"], fun o -> o.IsRequired <- true; o.Description <- "A list of words to be appended")
    let separator = Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")

    rootCommand argv {
        description "Appends words together"
        inputs (words, separator)
        setHandler app
    }
```

**Comment by JordanMarr** [comment]
[v0.9.0-beta] is released with a new `Input.OptionRequired` method.

Still contemplating adding a `configure` overload to allow setting other stuff like `Arity`.

**Comment by mrboring** [comment]
Hi

I'm new to `FSharp` and `FSharp.SystemCommandLine` (FSSCL). I'm looking to use FSSCL in a project. However, I'm finding that I have to use `System.CommandLine` (SCL) directly as I need access to other configuration items such as: `AllowMultipleArgumentsPerToken`, `ExistingOnly()` and `AddVdliator`. So I have a mixture of FSSCL and SCL. It doesn't look too bad, but I'm probably missing out on some FSharp helpfulness/safety by using SCL.

Adding a `configure` overload sounds like it would be useful.

**Comment by JordanMarr** [comment]
You can use these helper functions to provide the same functionality:

```F#
let configureOption (configure: System.CommandLine.Option -> unit) (input: HandlerInput<'T>) = 
    match input.Source with
    | ParsedOption o -> configure o
    | _ -> ()
    input

let configureArgument (configure: System.CommandLine.Argument -> unit) (input: HandlerInput<'T>) = 
    match input.Source with
    | ParsedArgument a -> configure a
    | _ -> ()
    input
```

Usage:
```F#

[<EntryPoint>]
let main argv = 
    let words = 
        Input.Option(["--word"; "-w"], Array.empty, "A list of words to be appended")
        |> configureOption (fun o -> o.ArgumentHelpName <- "word")

    let separator = Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")

    rootCommand argv {
        description "Appends words together"
        inputs (words, separator)
        setHandler app
    }
```

**Comment by mrboring** [comment]
Thanks for the functions. Unfortunately I get errors when I try to use them. 

The errors are for `HandlerInput.OfOption` and `HandlerInput.OfArgument` lines.

Sample code:

```f#
#r "nuget: System.CommandLine, 2.0.0-beta4.22272.1"
#r "nuget: FSharp.SystemCommandLine, 0.14.0-beta4"

open FSharp.SystemCommandLine
open System.CommandLine.Parsing

let configureOption (configure: System.CommandLine.Option -> unit) (input: HandlerInput<'T>) =
    match input.Source with
    | ParsedOption o ->
        configure o |> HandlerInput.OfOption
                        // Type constraint mismatch. The type
                        //     'unit'
                        // is not compatible with type
                        //     'System.CommandLine.Option<'a>'
    | _ ->
        input

let configureArgument (configure: System.CommandLine.Argument -> unit) (input: HandlerInput<'T>) =
    match input.Source with
    | ParsedArgument a ->
        configure a |> HandlerInput.OfArgument
                        // Type constraint mismatch. The type
                        //     'unit'
                        // is not compatible with type
                        //     'System.CommandLine.Argument<'a>'
    | _ ->
        input

let app (words: string array, separator: string option) =
    printfn $"words: %A{words}"
    printfn $"separator: %A{separator}"
    0

// [<EntryPoint>]
let main argv =

    let words =
        Input.Option(["--word"; "-w"], Array.empty, "A list of words to be appended")
        |> configureOption (fun o -> o.ArgumentHelpName <- "word")

    let separator =
        Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")
        |> configureOption (fun o -> o.IsHidden <- false)

    rootCommand argv {
        description "Appends words together"
        inputs (words, separator)
        setHandler app
    }

main [| "-w"; "w1"; "-w"; "w2"; "-w"; "w3"; "-s"; "#" |]
```

**Comment by JordanMarr** [comment]
Oops, that's what I get for writing code without an editor.

```F#    
let configureOption (configure: System.CommandLine.Option -> unit) (input: HandlerInput<'T>) = 
    match input.Source with
    | ParsedOption o -> 
        configure o 
        o :?> System.CommandLine.Option<'T> |> HandlerInput.OfOption<'T>
    | _ -> 
        input

let configureArgument (configure: System.CommandLine.Argument -> unit) (input: HandlerInput<'T>) = 
    match input.Source with
    | ParsedArgument a -> 
        configure a 
        a :?> System.CommandLine.Argument<'T> |> HandlerInput.OfArgument<'T>
    | _ -> 
        input

```

**Comment by mrboring** [comment]
Thanks for the quick response.

**Comment by JordanMarr** [comment]
Still trying to decide if this should be added as an overload to `Input.Option` and `Input.Argument` as I'm trying to avoid overload explosion.

The catch all is to just manually create a custom `System.CommandLine.Option(...)` when needed and then pipe it into `HandlerInput.OfOption`. 

But I can see how it might be nice to always be able to the use the `Input` helpers.

**Comment by JordanMarr** [comment]
It took some doing to avoid breaking any existing overloads (especially with the optional arguments), but I think it will be worth it.

New release:
https://github.com/JordanMarr/FSharp.SystemCommandLine/releases/tag/v0.15.0-beta4

Docs updated:
https://github.com/JordanMarr/FSharp.SystemCommandLine#setting-input-properties-manually

**Comment by mrboring** [comment]
This works great. Thanks. I did notice a small typo in the updated readme, and I've created a pull request.
