### ISSUE TITLE
Showing help menu / access to the rootCommand object

### ISSUE THREAD

**Issue by cgravill** [JordanMarr/FSharp.SystemCommandLine#7]
Really enjoying the library, I started to write some code like it when using System.CommandLine directly. Thanks for releasing it.

I'm trying to match an existing tool that shows help when run with no arguments, as in this issue: https://github.com/dotnet/command-line-api/issues/1449

I found myself a bit blocked as the rootCommand immediately executes so I don't have something to pass the HelpContext. I hacked up an approximate workaround but it behaves a little differently still:

```fsharp
let rec showHelp (helpBuilder:HelpBuilder) =
    let hc = new HelpContext(helpBuilder,fakeRoot,System.Console.Out);
    helpBuilder.Write(hc)
    0

and fakeRoot = command "fakeRoot" {
    description "Deploys stuff"
    inputs (helpBuilder)
    setHandler showHelp
    addCommand realCommand
}

rootCommand args {
    description "Deploys stuff"
    inputs (helpBuilder)
    setHandler showHelp
    addCommand realCommand
}
```

I saw you discussed this over on https://github.com/JordanMarr/FSharp.SystemCommandLine/issues/1#issuecomment-1067218760 as well. Am I missing a good way to do this?

**Comment by JordanMarr** [comment]
Colin, 
Thanks for the feedback! I'm happy to hear that you are enjoying the library.

We definitely need a way for the `rootCommand` to not auto-run. 

I'm trying to decide which approach would be best:

A) Add an `autoRun` operation that takes a boolean that defaults to true, but that you can manually set to `autoRun false`.
B) Create a new variation of the CE, `rootCommandDef` or similar that returns the actual `RootCommand`. 

I think I am leaning towards option A (or similar).

**Comment by cgravill** [comment]
Great! Any of those options looks like it would let me achieve what we're after.

Part of me also wonders if `rootCommand` should default cold and need the extra operation to make it auto-run, but I also really like the convenience you've achieved and most people are going to want to use it that way.

**Comment by cgravill** [comment]
Thanks for the super fast release!

That lets me remove the duplication and pass in the real command. In case anyone wants to see the full hack:

```fsharp
let rec showHelp (helpBuilder:HelpBuilder) =
    let hc = new HelpContext(helpBuilder,root.Configuration.RootCommand,System.Console.Out);
    helpBuilder.Write(hc)
    0

and root: CommandLine.Parsing.Parser = rootCommandParser {
    description "Deploys stuff"
    inputs (helpBuilder)
    setHandler showHelp
    addCommand realCommand
    addCommand realCommand2
}

root.Parse(args).Invoke()
```

**Comment by kentcb** [comment]
I think I have the same problem: it doesn't make sense to run my root command without a subcommand, and when I do I get no user feedback (unless I run with `--help`).

@cgravill  I'm not entirely clear on what `helpBuilder` is in the `inputs (helpBuilder)` line. Would you mind elaborating on how that is declared or obtained?

**Comment by JordanMarr** [comment]
It appears to be built-in to the framework:

[HelpBuilder.cs](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Help/HelpBuilder.cs)

**Comment by kentcb** [comment]
@JordanMarr That's the type, but I was referring to the instance of that type. I'm just not sure how to get hold of one.

**Comment by cgravill** [comment]
You can get an instance injected from the `Input` module. Here's a bit more of the code:

```fsharp
let envInput = Input.OptionRequired<string>(["--env"; "-e"], "Deployment environment (Earth, Moon, Mars)")

//More stuff

let helpBuilderInput = Input.InjectedDependency<HelpBuilder>()
```

**Comment by JordanMarr** [comment]
S.CL beta 4 changed the way dependency injection works, so now the only thing you can inject is the `BindingContext`. 
Consequently, `Input. InjectedDependency` has been replaced with `Input.Context`. 
So you may be able to call `ctx.GetService` to get an instance of the help builder.

**Comment by cgravill** [comment]
Good to know. We haven’t needed to update that project but will try that when we do

**Comment by JordanMarr** [comment]
So it turns out that S.CL beta 4 makes removes the need for the recursive binds for this help scenario because everything you need already lives directly on the `InvocationContext`:

```f#
open FSharp.SystemCommandLine
open System.CommandLine.Parsing
open System.CommandLine.Invocation
open System.CommandLine.Help
    
let appendCmd = 
    let handler (words: string array, separator: string option) =
        let separator = separator |> Option.defaultValue ", "
        System.String.Join(separator, words) |> printfn "Result: %s"
        
    let words = Input.Option(["--word"; "-w"], Array.empty, "A list of words to be appended")
    let separator = Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")

    command "append" {
        description "Appends words together"
        inputs (words, separator)
        setHandler handler
    }

[<EntryPoint>]
let main argv = 
    let ctx = Input.Context()

    let showHelp (ctx: InvocationContext) =
        let hc = HelpContext(ctx.HelpBuilder, ctx.Parser.Configuration.RootCommand, System.Console.Out)
        ctx.HelpBuilder.Write(hc)

    let root = 
        rootCommandParser {
            description "Appends words together"
            inputs (ctx)
            setHandler showHelp
            addCommand appendCmd
        }

    root.Parse(argv).Invoke()
```
