### ISSUE TITLE
Required, but may be found in an environment variable

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [JordanMarr/FSharp.SystemCommandLine#8]
I've never used `System.CommandLine` so I'm not sure if I should have some kind of familiarity there first.
Here is my first impression trying to use this today.

I have no clue and the documentation on this lib doesn't appear to be terribly clear on when I'd use `Input.Argument` vs `Input.Option`. My initial guess was that `Input.Option` was for things that weren't required. Now after trying to figure it out via the examples and intellisense, I'm guessing it is options have `-foo` proceeding them whereas arguments are positional?

The bigger issue I'm having is understanding how to have something that is required, but may be found (for instance in environment variables) elsewhere. I am leaning towards this type of argument location being more cleanly or conceptually not done in the handler. I'd love it if the concept of a handler was able to be ignorant of how the inputs were located, rather than it just being... here's the things we did find in the command line. 

Maybe I'm over generalizing the problem this aims to solve. if it really is meant to deal 100% only with the command line, and not have an escape hatch for people to have custom logic for locating inputs, then that's on me.

Possible workarounds (or maybe the way this was designed to be used):
 - I could use `Input.Option` with a default value of null/empty string when the environment variable also doesn't have it. con - I'd have to check the environment first, then have the handler show errors when it doesn't get a real value (completely eliminating the friendly error messaging, if any, this would show when we don't have a real value.)
 - I could try to handle validation/other methods of argument location in the handler. cons: we still lose the friendly error messaging possibility, handler has additional concerns

Since command line is the first line of configuration, and I'd like to only gather config values from other sources if I'm missing any from the command line, I'd love to be able to plug a `() -> 'T option` function in for the defaultThunk similar to `Option.orElseWith`. then if neither the command line nor the provided hatch gives a `Some 'T` then the user gets the nice command line options for how to provide it (even more optimally/optionally providing a way for the caller to add or customize the output so environment variable names could be shown.)

**Comment by JordanMarr** [comment]
Thanks for the feedback.

Some experience with System.CommandLine is perhaps expected, but not absolutely necessary.

`Argument` and `Option` are first class nouns in the underlying System.CommandLine domain. 
In System.CommandLine speak, `Argument` is a positional, unlabeled input. `Option` is an unordered, labeled input.

_Side note_: `Option` slightly conflicts with F# as it makes `Option` an overloaded term with F# `option` types. I chose to stick with their terminology. (I also added support for F# `option` input parameters via `Input.OptionMaybe` and `Input.ArgumentMaybe' which allow you to compute missing inputs within the handler fn, but I think that is not relevant to your issue).

My `Input` static methods are simply convenience wrappers for constructing S.CL inputs and transforming them for use with the computation expression. The underlying S.CL inputs actually do provide `getDefaultValue: unit -> 'T` overloads, but my current helpers were simplified to only take a default value (because that was convenient for my use case). However, in your case, it sounds like it would be useful to provide a `getDefaultValue` function to supply environment variables. 

Fortunately, you can easily extend the `Input` helpers:

```F#
type Input =

    static member OptionWithGetDefault<'T>(aliases: string seq, getDefaultValue: unit -> 'T, ?description: string) = 
        System.CommandLine.Option<'T>(
            aliases |> Seq.toArray,
            getDefaultValue = getDefaultValue,
            description = (description |> Option.defaultValue null)
        )
        |> HandlerInput.OfOption
```

## Usage

```F#
let app (words: string array, separator: string option) =
    let separator = separator |> Option.defaultValue ", "
    System.String.Join(separator, words) |> printfn "Result: %s"
    0
    

[<EntryPoint>]
let main argv = 

    let getWordsFromEnv () =
        [| "a"; "b" |]

    let words = Input.OptionWithGetDefault(["--word"], getWordsFromEnv, "A list of words to be appended")
    let separator = Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")

    rootCommand argv {
        description "Appends words together"
        inputs (words, separator)
        setHandler app
    }
```

**Comment by ImaginaryDevelopment** [comment]
Thanks for the detailed reply, however this doesn't appear to allow for the getDefault to return `None` as well, in such a way that your lib could error out rather than call the handler, providing documentation to the user of how to provide the missing value on the command line.

**Comment by JordanMarr** [comment]
Arguments that are created without defaults already do give feedback to the user that the input is required.
For Options, you can use `Input.OptionRequired` to show an error if the option is not provided.

**Comment by ImaginaryDevelopment** [comment]
Ok, maybe I'm doing a poor job explaining or maybe your answers are because string is a special case since it can be 'T (null or empty) and still not be valid as it conceptually is still an invalid `'T option` in those cases.

I want to have command line take precedence, falling back to a `'T option` or `unit -> 'T option`, not calling the handler, and giving error text that describes how to call the application when it doesn't find them.

`Input.OptionRequired` does not appear to have any overloads that allows for a defaultValue or tryGet function to be provided in case the command line doesn't find one.  If the provided default is `None` then this required value has failed to resolve one from the command line or the extra defaultValue plumbing, then it would error without calling the handler.

**Comment by JordanMarr** [comment]
It's hard to tell without any concrete examples, but the base S.CL library does provide validation. 
Here is an example that adds custom validation for a string option parameter:

```F#
module Program

open FSharp.SystemCommandLine

let app (name: string) =
    printfn $"Hello, {name}"
    
[<EntryPoint>]
let main argv = 

    let name = 
        let opt = System.CommandLine.Option<string>(
            "--name",
            getDefaultValue = (fun () -> ""),
            description = "User name")

        opt.AddValidator(fun result -> 
            let nameValue = result.GetValueForOption(opt)
            if System.String.IsNullOrWhiteSpace(nameValue)
            then result.ErrorMessage <- "Name cannot be an empty string."
            elif nameValue.Length > 10
            then result.ErrorMessage <- "Name cannot exceed more than 10 characters."
        )

        HandlerInput.OfOption opt

    
    rootCommand argv {
        description "Provides a friendly greeting."
        inputs name
        setHandler app
    }
```

**Comment by ImaginaryDevelopment** [comment]
ok I think I have what I want, but I don't think I used any of the F# helper lib, any tips on how to translate it to the helper?
```fs
type Opt<'t> = System.CommandLine.Option<'t>
type Arg<'t> = System.CommandLine.Argument<'t>

open System.CommandLine

[<EntryPoint>]

let main (argv: string array) =
    printfn "%A" argv

    // let inFile = Input.Argument<System.IO.FileInfo>("The file to import")
    let inFile = Arg<System.IO.FileInfo>("importFile","The file to import")

    let csOpt = Opt<string>(
        getDefaultValue=System.Func<_>(fun () -> getCsEnv() |> Option.defaultValue null),
        aliases=[| "-cs";"--connectionString" |],
        description="An optional connection string to the server to import into")

    let rc = System.CommandLine.RootCommand()
    rc.Add(inFile)
    rc.Add(csOpt)
    rc.SetHandler(app, inFile, csOpt)
    rc.Invoke argv
```

**Comment by JordanMarr** [comment]
TBH it looks great as-is, but I would do it like this if using the library:

```F#
module Program

open FSharp.SystemCommandLine

let getCsEnv() = 
    Some ""

let app (importFile: System.IO.FileInfo, connectionString: string) =
    printfn "Do stuff"

[<EntryPoint>]
let main (argv: string array) =

    let inFile = Input.Argument<System.IO.FileInfo>("importFile", "The file to import") 

    let csOpt = Input.Option(
        [ "-cs"; "--connectionString" ], 
        getCsEnv() |> Option.defaultValue null, 
        "An optional connection string to the server to import into")

    rootCommand argv {
        description "my app"
        inputs (inFile, csOpt)
        setHandler app
    }
```

A few notes:
1) The `app` handler function input args need to be passed as a tuple.
2) For the `csOpt` input, I used the `Input.Option` method and eagerly loaded the environment variable because it's probably not going to matter and I'm not into early optimization. However, you could also define it like this if you want to use the `getDefaultValue` function instead:

```F#
    open FSharp.SystemCommandLine.Aliases

    let csOpt = 
        Opt<string>(
            getDefaultValue = (fun () -> getCsEnv() |> Option.defaultValue null),
            aliases = [| "-cs";"--connectionString" |],
            description = "An optional connection string to the server to import into"
        )
        |> HandlerInput.OfOption
```

3) `open FSharp.SystemCommandLine.Aliases` already defines `Arg<'T>` and 'Opt<'T> aliases.
