### ISSUE TITLE
What would be the best way to bind records?

### ISSUE THREAD

**Issue by AngelMunoz** [JordanMarr/FSharp.SystemCommandLine#9]
Right now I guess there's not support for it and it is something hard to do in an F#'ish way

https://learn.microsoft.com/en-us/dotnet/standard/commandline/model-binding#use-a-custom-binder

my second guess would be to do it the same way as the article says which is likely to be the simplest one

any thoughts? feel free to close this if there's not a lot that can be done

**Comment by JordanMarr** [comment]
I was pondering your question and I came up with a very simple solution involving composition + a simple function to transform the expected tupled args into record form:

```F#
module Program

open FSharp.SystemCommandLine

type Cfg = 
    { 
        Words: string array
        Separator: string option 
    }

let buildCfg (words: string array, separator: string option) = 
    {  Words = words; Separator = separator }

let app (cfg: Cfg) =
    let separator = defaultArg cfg.Separator ", "
    System.String.Join(separator, cfg.Words) |> printfn "Result: %s"

    
[<EntryPoint>]
let main argv = 
    let words = Input.Option(["--word"; "-w"], Array.empty, "A list of words to be appended")
    let separator = Input.OptionMaybe(["--separator"; "-s"], "A character that will separate the joined words.")


    rootCommand argv {
        description "Appends words together"
        inputs (words, separator)
        setHandler (buildCfg >> app)
    }
```

Would that work for your use case?

**Comment by AngelMunoz** [comment]
It actually does!

I was wondering if I had to fall back to the plain lib, but this makes a lot of sense

I'll close this for the moment and poke back if have further questions, as I'm porting Perla's cli stuff to this library

**Comment by AngelMunoz** [comment]
such a clever solution btw, I would have never thought about it 😆

**Comment by JordanMarr** [comment]
Yeah I was kind of excited about that one too, because the proposition of adding custom support for the `BaseBinder` seemed like an inevitability that I was putting off. But this just seemed like another example of F# making complex things simple. 😀

Also, I took a quick stab at what I think it might look like using the `Remove` command:

https://github.com/AngelMunoz/Perla/compare/main...JordanMarr:Perla:SCL

**Comment by AngelMunoz** [comment]
Don't mind if I take that!? it looks very great

I'm sure I'll kind of do weird stuff until I get how to use it

but that removes a big concern of my head, thanks!

**Comment by JordanMarr** [comment]
Not at all! Feel free to use or change it however you see fit.

**Comment by JordanMarr** [comment]
One more tweak - it may be necessary to compose `processExit` into each command handler:

```F#
command "remove" {
  description "Removes stuff"
  inputs package
  setHandler (toRecord >> runRemove >> processExit)
}
```

Then `Program.fs` becomes simpler without being wrapped in a `taskResult`:

```F#
open Perla.Lib
open Types
open Logger
open FSharp.SystemCommandLine

[<EntryPoint>]
let main argv =
  Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "Development")

  rootCommand argv {
    description "Perla"
    //inputs ()                 // Add if a default handler is needed
    setHandler Task.FromResult  // Replace if default handler is needed
    addCommand Commands.runRemoveCmd
  }
  |> Async.AwaitTask
  |> Async.RunSynchronously
```

**Comment by AngelMunoz** [comment]
I will actually re-work how I'm using TaskResult all over the code base, I'm not really getting the extend and power of it since I'm just using `Result<'T, exn>` to be honest it doesn't make much sense and I locked myself into forcing everything to go that way 😓 

I have actually finished this part I'll put up a branch so you can take a peek how it ended up, suffice to say I haven't tested this yet because since I modified the fundamental types from the app, it is in a broken state for the moment

**Comment by AngelMunoz** [comment]
Here you go
https://gist.github.com/AngelMunoz/bfb1531ffb8a98abe10c98b06bb77dea

I guess that's easier to share at least for the moment

What I'm not sure if I will be able to do because I haven't tried it
is to have a root command handler + the sub command handlers and they not fighting each other

also rather than exposing it for each command I should consider exposing `--dev` as a global option but I'm not sure just yet

**Comment by JordanMarr** [comment]
Thanks for posting. That is a satisfying refactor!
Other people have had success with having a [Help Command](https://github.com/JordanMarr/FSharp.SystemCommandLine/issues/7#issuecomment-1194422812) as the main handler that executes if no command is specified, so it should work.

**Comment by JordanMarr** [comment]
I did a little spike to try adding a "global option" that your commands can use if needed.

```F#
module Program

open System.IO
open FSharp.SystemCommandLine

let isDevGlobal = Input.Option("--dev", "Dev mode enabled (global)")

let listCmd = 
    let handler (dir: DirectoryInfo, isDev: bool) = 
        printfn $"Dev mode enabled: {isDev}"

        if dir.Exists 
        then dir.EnumerateFiles() |> Seq.iter (fun f -> printfn "%s" f.FullName)
        else printfn $"{dir.FullName} does not exist."
        
    let dir = Input.Argument("directory", DirectoryInfo(@"c:\default"))

    command "list" {
        description "lists contents of a directory"
        inputs (dir, isDevGlobal)
        setHandler handler
    }

let deleteCmd = 
    let handler (dir: DirectoryInfo, recursive: bool) = 
        if dir.Exists then 
            if recursive
            then printfn $"Recursively deleting {dir.FullName}"
            else printfn $"Deleting {dir.FullName}"
        else 
            printfn $"{dir.FullName} does not exist."

    let dir = Input.Argument("directory", DirectoryInfo(@"c:\default"))    
    let recursive = Input.Option("--recursive", false)

    command "delete" {
        description "deletes a directory"
        inputs (dir, recursive)
        setHandler handler
    }

open System.CommandLine.Parsing

[<EntryPoint>]
let main argv = 
    rootCommand argv {
        description "File System Manager"
        setHandler id
        addCommands [ listCmd; deleteCmd ]
    }    
```
